### ISSUE TITLE
Installation commands not working

### ISSUE THREAD

**Issue by Timple** [Rayman/ros-get#1]
After the installation commands from the README.md on ubuntu 16.04 there is no ros-get command available. Probably because the .bashrc is not reloaded. 

Upon opening a new terminal I get this error:
`bash: /home/tim/catkin_ws/devel/setup.bash: No such file or directory`

**Comment by Timple** [comment]
This can be manually resolved by following the [ros install guide](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment)

```
$ mkdir -p ~/catkin_ws/src
$ cd ~/catkin_ws/src
$ catkin_init_workspace

$ cd ~/catkin_ws/
$ catkin_make
```

**Comment by Rayman** [comment]
This package has been rewritten. There is an issue for new installation instructions here: #11
