### ISSUE TITLE
Use colcon as default if a ROS2 installation is detected

### ISSUE THREAD

**Issue by Rayman** [Rayman/ros-get#103]
https://github.com/Rayman/ros-get/pull/101 a couple of ideas were brainstormed:

> Or sane defaults but you can override with --colcon and --catkin

```py
if args.colcon:
	make_ws_with_colcon():
elseif args.catkin::
	make_ws_with_catkin_tools():
else:
	automagically_detect_ws_tool()
```

**Comment by reinzor** [comment]
To be it feels a little bit weird that you can specify both. So I vote for the `--toolchain` option.
