### ISSUE TITLE
Add new installation instructions

### ISSUE THREAD

**Issue by Rayman** [Rayman/ros-get#11]

**Comment by reinzor** [comment]
After installing, I do now receive:

`pkg_resources.DistributionNotFound: The 'ros-get' distribution was not found and is required by the application
`

**Comment by Rayman** [comment]
Short version:
```sh
export ROSDISTRO_INDEX_URL=<url to your rosdistro>
rosdep update
```
My toy repository can be found [here](https://github.com/Rayman/rosdistro)

**Comment by reinzor** [comment]
I just created my own rosdistro, but it is still complaining ..

**Comment by reinzor** [comment]
@Rayman , could you provide a short instruction

**Comment by Timple** [comment]
A migration guide would also be appreciated :-)

For developers -> convert targets to rosdistro
For users -> painlessly switch to ros-get from tue-env
