### ISSUE TITLE
ros-get ws-switch should also update the ROSDISTRO URL

### ISSUE THREAD

**Issue by reinzor** [Rayman/ros-get#18]
I know that this feature is not yet in but we should not leave this to the user. If you are switching, you would also like to switch the distro url so we should store this in the ros-get config

**Comment by reinzor** [comment]
Also, if this feature is in, we do not need an additional setup.bash for a workspace / rosdistro. Then we can just point to the devel/setup.bash of using `$(ros-get ws-locate)/devel/setup.bash`

**Comment by Rayman** [comment]
Would it be a solution to just source the setup.sh of the workspace you're switching to?

From python you can't export environment variables, so some setup.sh is needed for these variables:
```
export ROSDISTRO_INDEX_URL=???
export ROS_ETC_DIR=$_WS_DIR/.etc
export ROS_HOME=$_WS_DIR/home
```

**Comment by reinzor** [comment]
I currently have this `setup.bash` for the environment (not workspace specific):

> _ENV_DIR=$(builtin cd "`dirname "${BASH_SOURCE[0]}"`" > /dev/null && pwd)
> 
> if ros-get ws-locate > /dev/null 2> /dev/null
> then
>     _WS_DIR=`ros-get ws-locate`
> 
>     source "$_WS_DIR/devel/setup.bash"
>     export ROS_ETC_DIR=$_WS_DIR/.etc
>     export ROS_HOME=$_WS_DIR/home
> 
>     export ROSDISTRO_INDEX_URL=file://$_ENV_DIR/rosdistro/$(basename `ros-get ws-locate`).yaml
> fi

I think this is quite neat but the ugly part is the last `export ROSDISTRO_INDEX_URL`; it would be nice to obtain this url from the ros-get tool, e.g. `ros-get ws-rosdistro-url`

**Comment by reinzor** [comment]
Solved by https://github.com/Rayman/ros-get/pull/25
