### ISSUE TITLE
Feature request: Command to obtain current workspace

### ISSUE THREAD

**Issue by reinzor** [Rayman/ros-get#19]
We do have `ros-get ws-locate` but it is also useful to obtain the name of the workspace and the associated `ROS_DISTRO_URL`

**Comment by reinzor** [comment]
However, if the ROS_DISTRO_URL is managed by the tool, this is debatable

**Comment by Rayman** [comment]
So somethink like:
```
readlink ~/.config/ros-get/workspace
```
But then implemented in python with appropriate error handling?

**Comment by reinzor** [comment]
For example, but we would also like to obtain the rosdistro url, as mentioned in https://github.com/Rayman/ros-get/issues/18
