### ISSUE TITLE
When there are no packages in the workspace, roscd switches to parent workspace

### ISSUE THREAD

**Issue by reinzor** [Rayman/ros-get#22]
Is this desired behavior?

**Comment by Rayman** [comment]
When you have no packages in the workspace, your `ROS_PACKAGE_PATH` is not yet set. `catkin_tools` does this per package. I don't know what we can do about it.

**Comment by Timple** [comment]
Just call it desired behavior ;-)

**Comment by Rayman** [comment]
Or an alias (not tested):
```sh
alias trunk='cd "$(readlink ~/.config/ros-get/workspace)/src"'
```

**Comment by reinzor** [comment]
That is up to the user I think.

-Rein

**Comment by Rayman** [comment]
So it's not a but in `ros-get`, closing
