### ISSUE TITLE
Feature request: Choose version of package.

### ISSUE THREAD

**Issue by Timple** [Rayman/ros-get#26]
For now we compile twist_mux from source (just an example).

It would be nice if we can choose between debian and source versions of packages (and that this choice is remembered over ros-get updates)

In future also convenient when you release debian files for whatever reason, you can then choose to develop or use a package.
Easy switching is key in this I think.

**Comment by Rayman** [comment]
You can already do this:
- source: add source to `kinetic/distribution.yaml`
- apt: add them to `rosdep/base.yaml`

Source goes before rosdep.

**Comment by Timple** [comment]
But this means a custom distribution.yaml for every developer?

At tue I don't mind about the move_base packages but I do develop in perception packages. Another team member might want this the other way around.

**Comment by Rayman** [comment]
You share the distribution.yaml in your team. But if you want a different behavior locally, you can of cource just edit the file locally

**Comment by reinzor** [comment]
I think this issue can be closed
