### ISSUE TITLE
Discussion on this installer / ros pkg manager

### ISSUE THREAD

**Issue by reinzor** [Rayman/ros-get#6]
@Timple @Rayman , idea to discuss the future of this installer / pkg manager. I would like to develop and test on this but I think we should align a bit more first :)

**Comment by Timple** [comment]
Aligning seems like a good idea!

I like the idea that it depends on existing tools (vcstool, rosdep). I'll dump some thoughts here to jumpstart a discussion:

#### Requirements:
- ros-get install package
- ros-get update [package]
- Clean (small) codebase

#### Nice to haves:
- ros-get remove [package]
- Release capability (generate debians)
- Choose and switch between apt and src version of packages

I'm willing to come to the tue for a discussion on this.

**Comment by Rayman** [comment]
I have some ideas about the install and update commands [see here](https://github.com/Rayman/ros-get/blob/c8d6b9b69d58e676d1ce0343186902a51a785b0b/src/ros_get/commands.py). We can discuss this by phone.

 But I don't know how to build debians. Did you guys see a presentation about that on roscon?

**Comment by reinzor** [comment]
Should we discuss next tuesday? Just half an hour?

-Rein

**Comment by reinzor** [comment]
Discussion of today:

- we need rosdistro/ws functionality to switch between workspaces, a workspace is basically a ros distro file (we should be able to overlay these distro files)
- If you switch to another workspace, you can install packages and its dependencies will then be resolved with use of the ros distro file
- If you are working on multiple projects, you can define a workspace per project, so a ros distro file per project. This way, you can use specific versions of packages in your project since these can be specified with tags etc in the ros distro file

**Comment by Rayman** [comment]
@reinzor I was testing this weekend to see how fast an `rosdistro_build_cache --include-source` call takes. For all amigo repos (106), it takes aound 1 minute. Is that acceptable? We could trim the amount of repos to get this number down.

**Comment by reinzor** [comment]
I do think this is acceptable.

106 repo's is just a lot xD.

Let's discuss Tuesday.

-Rein

**Comment by Rayman** [comment]
I've put all the output of the discussion in #3, started a rewrite in the `rewrite` branch

**Comment by Timple** [comment]
I'll just discuss here, todo's can go to #3.

Everything is very ROSsig. Do we still want to support custom targets? They have proven to be useful but are not perse ROS related.

Maybe a plugin like solution like the `.d` folders in linux. Like `/etc/apt/sources.list.d/`

User targets or tue-specific targets can than be in a different repo and do not clutter other (nicer-maintained?) repos.

PS. I'll try to visit again soon, let me know if anything needs testing :)

**Comment by Rayman** [comment]
What are custom targets? What I have now is the following:
- system dependencies (apt-get, pip etc. that are installed with rosdep, also custom bash scripts can be created)
- packages and meta packages just like normal ROS packages. They can have catkin hooks for aliases or environment variable setting

Your own distribution should go in a different repo. An example can be found here: https://github.com/Rayman/rosdistro

**Comment by reinzor** [comment]
I think what @Timple is referring to is custom bash scripts, e.g. openpose, openface, sublime, vim (in the tue-env repo).
