### ISSUE TITLE
Should ros-get update checkout the correct version of the repository?

### ISSUE THREAD

**Issue by reinzor** [Rayman/ros-get#85]
When you run a `ros-get update` and your rosdistro file has changed from version `1.0.0` to `1.2.0`, the `ros-get` tool does not check out the correct branch / tag. Is this the behavior we want? I think implementing this is fairly straight forward but it might be annoying if you are working on a branch and you run an update, the `ros-get` tool switches the branch for you. @Rayman , what do you think about this?

**Comment by reinzor** [comment]
Now you can achieve a "clean update" by removing the folders in your `repos` folder and run a `ros-get update`. However, this also feels a little bit hacky...

**Comment by Rayman** [comment]
When you do `ros-get status` you can see which repos are on the wrong branch. Should there be a flag or command to check out all the repos on the correct branch?

**Comment by reinzor** [comment]
That would be a nice feature: `ros-get update --flag_name`. Hard thing here is to figure out the name of the flag ;)

**Comment by reinzor** [comment]
Maybe `--restore-versions` ?

**Comment by reinzor** [comment]
or `update-versions`

**Comment by reinzor** [comment]
`--checkout-versions`

**Comment by reinzor** [comment]
@Rayman , what do you think of:

`ros-get update --update-versions`?

**Comment by Rayman** [comment]
I like `--checkout-versions`.

Is this feature also useful for CI where you have a rosdistro with flattened versions?

**Comment by Timple** [comment]
Newest git symantics is actually `git switch` instead of `git checkout`. So maybe adhere to that one already

**Comment by reinzor** [comment]
I am fine with:

`--checkout-versions`
`--switch-versions`
`--restore-versions` (preference since you restore the user modified versions)

**Comment by reinzor** [comment]
> I like `--checkout-versions`.
> 
> Is this feature also useful for CI where you have a rosdistro with flattened versions?

For CI, we keep the distro in the repo of the project. So this is already fine.

More for restoring a modified workspace IMO.

**Comment by reinzor** [comment]
@Rayman , should we go for `--checkout-versions` or `--restore-versions`?

**Comment by Rayman** [comment]
I don't have a preference, just pick one
