### ISSUE TITLE
Option to not do a rosdep update but a rosdep check

### ISSUE THREAD

**Issue by reinzor** [Rayman/ros-get#99]
`rosdep` also has an option to check whether all dependencies are met. Could we add this option to `ros-get` as well? This way, we can create a base image that includes our dependencies and only update our sources using `ros-get` but still check whether all deps are met.

@Rayman what do you think?

**Comment by reinzor** [comment]
command to check:

```
rein@laptop $ rosdep check --from-path -y -i . 
All system dependencies have been satisfied
```

**Comment by reinzor** [comment]
Maybe something like:

```
ros-get install --no-rosdep-install  # Only check dependencies using rosdep check
```
?

**Comment by Rayman** [comment]
So this would checkout all repositories, update the symlinks and then execute rosdep check?

**Comment by reinzor** [comment]
Yes

**Comment by reinzor** [comment]
@Rayman , I could implement something like this; open for a PR? Any suggestions on the `cmd line args` ?

**Comment by Rayman** [comment]
I'm not sure. What about one of these?
`ros-get install ... --check-dependencies`
`ros-get install ... --skip-install-dependencies`
`ros-get install ... --no-install-dependencies`

**Comment by reinzor** [comment]
I think we have to make a distinction between source dependencies and `rosdep` dependencies or not?

**Comment by Rayman** [comment]
Ah yes, good point

**Comment by reinzor** [comment]
So, any other suggestions besides `--no-rosdep-install` ;) ? Something with `check` maybe?

**Comment by Rayman** [comment]
Just pick a name that you like. 

You mean `--rosdep-check-install`?

**Comment by reinzor** [comment]
Fine with me :+1:
